server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: routes
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true